all:		Colleen Grace

clean:
	rm -f Colleen

fclean:		clean

re:			fclean all

Colleen:	Colleen.c
	gcc -Wall -Wextra -Werror Colleen.c -o Colleen

Grace:		Grace.c
	gcc -Wall -Wextra -Werror Grace.c -o Grace

.PHONY:		all clean fclean re
